config/routes.rb
Gitgrove::Application.routes.draw do
  match "*path" => NanocServer.new, :constraints => SitesController.new
  resources :sites do
    collection do
      get 'dashboard'
      get 'index' => redirect('/sites/dashboard')
    end
    member do
      get 'rebuild'
    end
    resources :documents, :constraints => {:id => /.+/} do
      member do
        get 'history'
        post 'revert'
        post 'compare'
        match 'do_compare/*versions' => 'documents#do_compare'
      end
    end
    
    resources :assets, :constraints => {:id => /.+/} do
      member do

      end
    end
  end
  resources :users

  match '/auth/:service/callback' => 'services#create' 
  match '/auth/failure' => 'services#failure'
  match "/sites/dashboard", :as => :dashboard
  match "/services/signin", :as => :signin
  match "/services/signout", :as => :signout

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end
  match '/index.html' => 'pages#index', :as => :homepage
  match ':page', :controller => 'pages', :action => 'show', :page => PagesController::PAGES
  root :to => redirect('/index.html')
end

app/models/site.rb
require 'grit'
require 'fileutils'
class Site < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_sites
  
  after_create :setup_repo
  before_destroy :remove_repo

  state_machine :initial => :unbuilt do
    after_transition any => :queued do |site, trans| 
      Delayed::Job.enqueue(SiteBuildJob.new(site.id))
    end

    event :queue_build do
      transition [:unbuilt, :built, :error] => :queued
    end

    event :dequeue do
      transition :queued => :building
    end

    event :finish do
      transition :building => :built
    end

    event :exception do
      transition any => :error
    end
  end

  def setup_repo
    self.rebuild_token = rand(36**8).to_s(36)

    FileUtils.mkdir_p(Yetting.repo_storage_path) if(!File.exists?(Yetting.repo_storage_path))
    self.repo_path = "#{Yetting.repo_storage_path}/#{self.url}.git"
    clone = "#{Yetting.repo_storage_path}/_template_site.git"
    
    if(File.exists?(clone))
      Grit::Repo.init_bare(self.repo_path, :template => clone)
    else
      Grit::Repo.init_bare(self.repo_path)
    end


    preview_repo_setup

    self.save
    start_build!
  end

  def preview_repo_setup
    if(!File.exists?(preview_path))
      FileUtils.mkdir_p(Yetting.preview_storage_path) if(!File.exists?(Yetting.preview_storage_path))
      git = Grit::Git.new(Yetting.preview_storage_path)
      git.clone({}, self.repo_path, preview_path)
    end
  end
  
 
  
  def remove_repo
    FileUtils.rm_rf(self.repo_path) if self.repo_path
  end

  def preview_path
    "#{Yetting.preview_storage_path}/#{self.url}"
  end

  def start_build!
    self.queue_build if self.can_queue_build?
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_filter :authenticate_user!, :except => [:rebuild]
  def dashboard
    @sites = Site.all
  end

  def new
    admin_only!
    @site = Site.new
  end

  def create
    @site = Site.new(params[:site])
    if(@site.save)
      # Fix hook
      hook_name = File.join(@site.repo_path, 'hooks', 'post-receive')
      rebuild_url = rebuild_site_url(@site, :token => @site.rebuild_token, :only_path => false)
      text = File.read(hook_name)
      
      text.gsub!(/REBUILD_URL/, rebuild_url)
      File.open(hook_name, "w") {|file| file.puts text}
      File.chmod(0755, hook_name)


      redirect_to dashboard_path
    else
      redirect_to dashboard_path
    end
  end

  def rebuild
    @site = Site.find_by_id(params[:id])
    unless params[:token] == @site.rebuild_token
      redirect_to(dashboard_path) and return
    end
    @site.start_build!
    render :text => "Rebuild queued.\n"
  end


  def destroy
    site = Site.find_by_id(params[:id])
    site.destroy
    redirect_to dashboard_path
  end



  def matches?(request)
    first_path_part = request.fullpath.split('/')[1]
    s = Site.find_by_url(request.host.split('.').first)
    if s
      request.env['gitgrove_site_by_domain'] = true
    else
      s = Site.find_by_url(first_path_part)
    end
    if(s)
      request.env['gitgrove_site_url'] = s.url
      request.params['site_url'] = s.url
      true
    else
      false
    end
  end 
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.haml
= form_for(@site) do |f|
  %p
    = f.label(:name)
    %br
    = f.text_field(:name)
  %p
    = f.label(:url)
    %br
    = f.text_field(:url)
  = f.submit 'Create'

app/views/sites/dashboard.html.haml
%section.sites
  %p welcome #{current_user.name}
  %p This is a list of sites:
  #site_list
    - @sites.each do |s|
      .site{:class => s.state}
        .actions
          - if(current_user.admin?)
            .minibutton= link_to 'Delete', site_path(s), :method => :delete, :confirm => "Are you sure?"
          .minibutton= link_to 'Edit', site_documents_path(s) 
          .minibutton
            %a{:href => "http://#{with_subdomain(s.url)}/index.html"} Preview
        %p= s.name
        - if(s.error?)
          %p Last rebuild experienced an error.
        - if(s.building? || s.queued?)
          %p Site will be rebuilt
        - if(current_user.admin?)
          %p= File.join(Yetting.repo_clone_url, File.basename(s.repo_path))
          - if(Yetting.respond_to?(:archives_path))
            .actions
              .minibutton= link_to 'Download Zip', '/'+File.join(File.basename(Yetting.archives_path), "#{s.url}.zip")
  - if current_user.admin?
    .actions
      .minibutton= link_to 'Create New Site', new_site_path

app/views/sites/edit.html.haml
- @repo.pages.each do |page|

  .file
    %h1= page.title
    %h2 (#{page.path.gsub(/^content\//, '')})

app/views/sites/new.html.haml
%p Ready to create a new site?
= render('sites/form')