config/routes.rb
Gitgrove::Application.routes.draw do
  match "*path" => NanocServer.new, :constraints => SitesController.new
  resources :sites do
    collection do
      get 'dashboard'
      get 'index' => redirect('/sites/dashboard')
    end
    member do
      get 'rebuild'
    end
    resources :documents, :constraints => {:id => /.+/} do
      member do
        get 'history'
        post 'revert'
        post 'compare'
        match 'do_compare/*versions' => 'documents#do_compare'
      end
    end
    
    resources :assets, :constraints => {:id => /.+/} do
      member do

      end
    end
  end
  resources :users

  match '/auth/:service/callback' => 'services#create' 
  match '/auth/failure' => 'services#failure'
  match "/sites/dashboard", :as => :dashboard
  match "/services/signin", :as => :signin
  match "/services/signout", :as => :signout

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end
  match '/index.html' => 'pages#index', :as => :homepage
  match ':page', :controller => 'pages', :action => 'show', :page => PagesController::PAGES
  root :to => redirect('/index.html')
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
  <title><%= t :app_name %></title>
  <%= stylesheet_link_tag 'styles' %>
  <%= csrf_meta_tag %>
  <script src="/javascripts/libs/modernizr.js"></script>
  <script src="/javascripts/libs/respond.min.js"></script>
  <link rel="stylesheet" type="text/css" href="/css/gollum.css" media="all">
  <link rel="stylesheet" type="text/css" href="/css/editor.css" media="all">
  <link rel="stylesheet" type="text/css" href="/css/dialog.css" media="all">
  <link rel="stylesheet" type="text/css" href="/css/template.css" media="all">
  
  <!--[if IE 7]>
  <link rel="stylesheet" type="text/css" href="/css/ie7.css" media="all">
  <![endif]-->
  
</head>
<body id="<%= @location_id || "home" %>">
  <div id="container">
    <header id="header">

      <h1><%= t :app_name %></h1>
      <% if user_signed_in? && current_user.admin? %>
        <%= link_to "Manage Users", users_path %>
      <% end %>
      <% if user_signed_in?  %>
        <%= link_to "Log out", signout_path %>
        <%= link_to "Sites", dashboard_path %>
      <% end %>
    </header>
    <div id="main" role="main">
      <% if flash[:error] %>
        <div class="flash error"><p><%= flash[:error] %></p></div>
      <% end %>
      <% if flash[:notice] %>
        <div class="flash notice"><p><%= flash[:notice] %></p></div>
      <% end %>
      <%= yield %>
    </div>
    <footer id="footer">

    </footer>
  </div> <!--! end of #container -->

<!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="/javascripts/libs/jquery.min.js">\x3C/script>')</script>
  <%= javascript_include_tag 'rails' %>
</body>
</html>